module.exports = [
    "pretend lovers",
    "strong female lead",
    "adapted to anime",
    "childhood friend",
    "strong male lead",
    "age gap",
    "love triangle",
    "collection of stories",
    "character growth",
    "full color",
    "magic",
    "glasses-wearing male lead",
    "dead family member",
    "student",
    "big breasts",
    "possessive lover",
    "special ability",
    "beautiful female lead",
    "unrequited love",
    "high school",
    "cross-dressing",
    "handsome male lead",
    "misunderstanding",
    "student-teacher relationship",
    "demon",
    "older female younger male",
    "appearance different from personality",
    "male lead falls in love first",
    "tsundere",
    "incest",
    "secret identity",
    "friends become lovers",
    "based on a novel",
    "older male younger female",
    "past plays a big role",
    "slow romance",
    "high school student",
    "twin",
    "revenge",
    "live-in lover",
    "borderline h",
    "japan",
    "web comic",
    "female fighter",
    "friendship",
    "time skip",
    "21st century",
    "smart male lead",
    "tragic past",
    "murder",
    "jealousy",
    "older uke younger seme",
    "bullying",
    "orphan",
    "first love",
    "royalty",
    "animal characteristics",
    "student-student relationship",
    "monster",
    "vampire",
    "young male lead",
    "delinquent",
    "smart female lead",
    "unexpressed feeling",
    "popular male lead",
    "flashbacks",
    "bishounen",
    "love at first sight",
    "romantic subplot",
    "award-winning work",
    "amnesia",
    "cohabitation",
    "adapted to drama cd",
    "betrayal",
    "human-nonhuman relationship",
    "master-servant relationship",
    "mafia",
    "hard-working protagonist",
    "hidden past",
    "fellatio",
    "important non-romantic relationship",
    "european ambiance",
    "reincarnation",
    "love confession",
    "male demographic with female lead",
    "quirky character",
    "brother complex",
    "war",
    "neighbor",
    "rushed ending / axed",
    "club",
    "family",
    "swordsman",
    "arranged marriage",
    "violence",
    "webtoon",
    "unexpected feelings",
    "blackmail",
    "love polygon",
    "ghost",
    "appearance different from actual age",
    "reunion",
    "transformation",
    "weak to strong",
    "princess",
    "kidnapping",
    "loneliness",
    "spirit",
    "brother",
    "prince",
    "absent parent",
    "senpai-kouhai relationship",
    "dark ambience",
    "virgin",
    "transfer student",
    "adapted to live action",
    "older seme younger uke",
    "assassin",
    "playboy",
    "opposites attract",
    "sadist",
    "god",
    "time travel",
    "reverse harem",
    "post-secondary school",
    "episodic",
    "rivalry",
    "angst",
    "otaku",
    "rich male lead",
    "death of loved one",
    "student council",
    "training",
    "caught in the act",
    "unrequited love becomes requited",
    "office worker",
    "dead parent",
    "lust",
    "character who bullies the one they love",
    "teamwork",
    "cunnilingus",
    "school girl",
    "married couple",
    "maid",
    "stepsiblings",
    "genius",
    "boss-subordinate relationship",
    "female lead falls in love first",
    "emotionally strong female lead",
    "calm protagonist",
    "cool male lead",
    "teacher",
    "survival",
    "doctor",
    "multiple protagonists",
    "salaryman",
    "antihero / antiheroine",
    "bickering love",
    "insecurity",
    "tomboy",
    "bodyguard",
    "cat",
    "outdoor intercourse",
    "nobility",
    "gun",
    "siblings",
    "bisexual character",
    "prodigy",
    "detective",
    "childcare",
    "curse",
    "childhood trauma",
    "music",
    "secret organization",
    "protagonist strong from the start",
    "writer",
    "transported to another world",
    "sadomasochism",
    "debt",
    "obsessive love",
    "best friends",
    "glasses-wearing female lead",
    "threesome",
    "rich female lead",
    "childhood love",
    "contract",
    "young female lead",
    "sister complex",
    "post-secondary student",
    "sword and sorcery",
    "military",
    "kind male lead",
    "dead lover",
    "witch",
    "clever protagonist",
    "small breasts",
    "suicide",
    "naive female lead",
    "weak male lead",
    "clumsy protagonist",
    "trap",
    "coworker",
    "androgynous male lead",
    "dragon",
    "strategic minds",
    "child abuse",
    "workplace romance",
    "acting",
    "single parent",
    "manly gay couple",
    "school boy",
    "social hierarchy",
    "stalker",
    "secret relationship",
    "comic artist",
    "swordplay",
    "couple growth",
    "animal transformation",
    "foreigner",
    "dormitory",
    "alien",
    "esp",
    "younger sister",
    "modeling",
    "4-koma/yonkoma",
    "attempted murder",
    "rich protagonist",
    "sister",
    "lifestyle change",
    "yandere",
    "politics",
    "arrogant male lead",
    "pervert",
    "food",
    "all-boys school",
    "collection of inter-linked stories",
    "independent female lead",
    "subtle romance",
    "fast romance",
    "personality change",
    "inferiority complex",
    "strong-willed female lead",
    "showbiz",
    "split personality",
    "younger brother",
    "forbidden love",
    "coming of age",
    "cousin",
    "adapted to movie",
    "panchira",
    "knight",
    "innocent female lead",
    "loner protagonist",
    "prostitute",
    "love-hate relationship",
    "inexperienced in love",
    "all-girls school",
    "cosplay",
    "talented male lead",
    "psychopath",
    "angel",
    "popular female lead",
    "artist",
    "conspiracy",
    "world travel",
    "marriage",
    "tournament",
    "award-nominated work",
    "drunken intercourse",
    "university student",
    "dead friend",
    "game elements",
    "misunderstood protagonist",
    "stolen kiss",
    "undergarment",
    "shameless female lead",
    "pregnancy",
    "korea",
    "game",
    "part-time job",
    "social outcast",
    "accident",
    "exhibitionism",
    "experiment",
    "crime",
    "dream",
    "roommates",
    "serial killer",
    "school intercourse",
    "double / multiple penetration",
    "isekai",
    "appearance changes",
    "first kiss",
    "super powers",
    "mature child",
    "drug",
    "fetish",
    "gang",
    "comedic undertone",
    "businessman / businesswoman",
    "masochist",
    "ninja",
    "serioustudious character",
    "rich family",
    "injury",
    "tall male lead",
    "werewolf",
    "competition",
    "female dominance",
    "changed by love",
    "immortality",
    "police officer",
    "classmate",
    "slave",
    "family drama",
    "affectionate seme",
    "extended flashbacks",
    "reincarnated in another world",
    "police",
    "female demographic with male lead",
    "elf",
    "idol",
    "deception",
    "cold male lead",
    "perverted female lead",
    "stepsibling love",
    "sudden appearance",
    "scar",
    "host/hostess",
    "talented female lead",
    "demon lord/king",
    "love interests who don't get along",
    "politics involving royalty",
    "armed combat",
    "robot",
    "torture",
    "body swap",
    "parental abandonment",
    "short male lead",
    "older brother",
    "samurai",
    "hot-blooded male lead",
    "emotionally weak female lead",
    "swimsuit",
    "guilt",
    "regret",
    "attempted suicide",
    "rich kid",
    "naive male lead",
    "actor",
    "bromance",
    "cooking",
    "ambitious goal",
    "zombie",
    "middle school",
    "guardian relationship",
    "chasing after love interest",
    "fantasy world",
    "future",
    "abandoned children",
    "travel",
    "wish",
    "childhood promise",
    "older sister",
    "manipulation",
    "discrimination",
    "exorcism",
    "brother and sister",
    "marriage proposal",
    "adapted to game",
    "adapted to manga",
    "first-time intercourse",
    "dense protagonist",
    "kuudere",
    "second change",
    "depression",
    "limited lifespan",
    "zennomi",
    "licensed",
    "male protagonist",
    "teasing protagonist",
    "white-haired female lead",
    "short chapter",
]